name: Unit Tests
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [windows-latest] # Замените на имена ваших бегущих runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
